# Generated by Django 4.2 on 2024-09-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date'], 'verbose_name': 'Платежи'},
        ),
    ]
