# Generated by Django 4.2 on 2024-09-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(verbose_name="Дата оплаты"),
        ),
    ]
