# Generated by Django 4.2 on 2024-09-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="paid_course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="paid_lesson",
            new_name="lesson",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_method",
            new_name="method",
        ),
    ]
