# Generated by Django 4.2 on 2024-09-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0003_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-id"], "verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["-id"], "verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
