# Generated by Django 4.2 on 2024-10-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0004_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="edu.course"
            ),
            preserve_default=False,
        ),
    ]
