# Generated by Django 4.2 on 2024-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0005_alter_lesson_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Время последнего изменения"),
        ),
    ]
