# Generated by Django 4.2 on 2024-10-01 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0006_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 1, 12, 24, 6, 849375, tzinfo=datetime.timezone.utc),
                verbose_name="Время последнего изменения",
            ),
        ),
    ]
