# Generated by Django 4.2 on 2024-10-01 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0007_alter_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Время последнего изменения"),
        ),
    ]
